env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "cTcMJYMkpuMrV4tVHLKZqNeGNyMEZVjIH+vTqnEchFkafOerY9vrOs406FFtLMKCCnSKCt4KID+ljaS4DLLp2FeBSDKURau/7GwzlX5CholRmG1+Y1uqAFEopcsTijxkmQPM7JrBWgYh16UoOFfX2k5DKnGjd5QwaqgGOCcY91k="

addons:
  coverity_scan:
    project:
      name: "pavlinux/ctorrents-plx"
      description: "Console Torrent Client"
    notification_email: pavel@pavlinux.ru
    build_command_prepend: "make clean"
    build_command: "make -j4"
    branch_pattern: master

compiler:
  - gcc
  - g++

script:
  - make -j4
  - if [ "${COVERITY_SCAN}" = '1' ]; then eval "$COVERITY_SCAN_BUILD"; else eval "$STANDARD_BUILD_COMMAND"; fi

